### ISSUE TITLE
[🐞] v1.2.0 SuitcaseJS module not found

### ISSUE THREAD

**Issue by ghost** [TBroz15/SuitcaseJS#10]
### Which component is affected?

CLI

### Is it a dependency(ies) related problem?

No

### Describe the bug

![image](https://github.com/user-attachments/assets/0544925f-874b-4fc8-a9aa-477c6e035afc)
![image](https://github.com/user-attachments/assets/694ec164-11b8-4b76-8c7a-25cc04347299)
clear_cache.js was not included when pushed to npm

### Steps to reproduce

install the latest versions
run any command
then it comes back with the error in the previous box

**Comment by TBroz15** [comment]
@Goofy9506 Found out a build related issue, rn working on a fix.

**Comment by TBroz15** [comment]
v1.2.1 is ready
