### ISSUE TITLE
[🚀] config file

### ISSUE THREAD

**Issue by ghost** [TBroz15/SuitcaseJS#8]
### Describe the problem

Using a directory with more than just the RP and BP folders brings an error because of the node_modules and other files that are in the directory.

### Describe the solution

Just making a simple config file like .suitcase or suitcase.json would be nice. you would be able to do ignore folders/files in there and make additional changes aswell.

**Comment by ghost** [comment]
ill see if i can throw something together real quick in a pr

**Comment by ghost** [comment]
nvm pc pooped on itself

**Comment by TBroz15** [comment]
**Config files are planned to be added alongside with image compression**, but you can have a work around with this, just don't include node_module on your pack!

You can try this folder structure
![image](https://github.com/user-attachments/assets/4cc02c1a-0601-4f84-8095-d51607fe5a5c)

And inside of the packs folder is where all of the packs will be compiled.
![image](https://github.com/user-attachments/assets/00e69053-fda9-4ced-9483-cd1ecf0a2ea8)

Just run this and everything is fine.
```cmd
suitcase --compile "default" --in "./packs/" --out "./pack.mcpack"
```

**Comment by TBroz15** [comment]
I have something planned about the config file as a typescript file to make it type safe. You can do a PR if you are up to a challenge
